Repository UNLV-CS472-672/2024-S-GROUP5-Munch, pull requests merged in 2024-04, with the labels that each got.

#72 Refactor Post Component
  frontend/app/(modals)/comments.tsx
  frontend/app/(tabs)/Subtabs/recipe.tsx
  frontend/app/(tabs)/_layout.tsx
  frontend/app/(tabs)/index.tsx
  frontend/app/(tabs)/post/[id].tsx
  frontend/app/_layout.tsx
  frontend/app/post/[id].tsx
  frontend/app/utils/getCurrentDateTime.tsx
  frontend/app/utils/typeGuard.ts
  frontend/components/Comment.tsx
  frontend/components/Post.tsx
  frontend/components/Post/ButtonIcon.tsx
  frontend/components/Post/Post.tsx
  frontend/components/Post/icons.ts
  frontend/components/recipe.tsx
  frontend/package.json
  frontend/tamagui.config.ts
  frontend/types/post.ts
Labels: refactor

#73 Fixing Test Errors and Updating Test Cases
  backend/.gitignore
  backend/run_tests.py
  backend/unit_tests/test_create_delete_user.py
  backend/unit_tests/test_get_update_user.py
  backend/unit_tests/test_post_validation.py
  backend/unit_tests/test_posts.py
  backend/unit_tests/test_users.py
Labels: fix

#63 Like routes
  backend/like_routes.py
  backend/post_routes.py
  backend/run_tests.py
  backend/server.py
  backend/unit_tests/test_likes.py
  backend/unit_tests/test_posts.py
  backend/unit_tests/test_users.py
  backend/user_routes.py
Labels: feature, test

#78 Follow routes
  backend/follow_routes.py
  backend/server.py
Labels: feature

#96 Create Post Backend Functionality
  frontend/app/(tabs)/create.tsx
Labels: feature

#103 Create Post Refactor UI
  frontend/app/(tabs)/create.tsx
Labels: refactor

#101 Add Like Button Functionality
  frontend/app/(tabs)/feed.tsx
  frontend/app/(tabs)/friends.tsx
  frontend/components/Post/LikeButton.tsx
  frontend/components/Post/Post.tsx
Labels: feature

#104 Fix Android White Bar Profile Page - Issue #84
  frontend/app/(tabs)/profile/index.tsx
Labels: fix

#130 Store image into firestore cloud database
  backend/helper_functions.py
  backend/routes/post_routes.py
  backend/routes/recipe_routes.py
  backend/server.py
  frontend/app/(tabs)/create.tsx
  frontend/components/Post/Post.tsx
Labels: feature, fix

#134 Feed page
  .gitignore
  backend/routes/yelpAPI/fakeDataAPI.py
  backend/server.py
  frontend/app/(tabs)/_layout.tsx
  frontend/app/(tabs)/activity.tsx
  frontend/app/(tabs)/feed.tsx
  frontend/app/(tabs)/index.tsx
Labels: feature, fix
